In [1]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.2.2'

In [5]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"

data = pd.read_csv(url)

In [7]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [9]:
data.count() #counting per columns
print("Row count: ",len(data))

Row count:  20640


In [11]:
print("Columns count: ", len(data.columns) )

Columns count:  10


In [13]:
#checking columns with missing values

data.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [15]:
data['ocean_proximity'].nunique()

5

In [17]:
data['ocean_proximity'].unique() #check the unique values in Ocean Proximity

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [19]:
# data[data["ocean_proximity"] == "NEAR BAY"].median_house_value.mean()
data[data["ocean_proximity"] == "NEAR BAY"]["median_house_value"].mean()

259212.31179039303

In [21]:
total_bedroom_mean = data['total_bedrooms'].mean()
total_bedroom_mean

537.8705525375618

In [23]:
data["total_bedrooms"]= data['total_bedrooms'].fillna(total_bedroom_mean)

In [25]:
data.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [27]:
data.total_bedrooms.mean()

537.8705525375617

#### Question 7

It looks like the hard one here!

1. Select all the options located on islands. <br>
2. 
Select only columns housing_median_age, total_rooms, total_bedrooms<br>.3. 
Get the underlying NumPy array. Let's call it <br>X4. .
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result X<br>T5. X.
Compute the inverse of <br>X6. TX.
Create an array y with values [950, 1300, 800, 1000, 1<br>37. 00].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the res<br>u8. lt w.
What's the value of the last elemen<br>t of w?
Note: You just implemented linear regression. We'll talk about it in the next<br> l    esson.
<br>
    
-1.<br>4    812
0<br>.    001
5.<br>6992
23.1233

In [30]:
island_data = data[data["ocean_proximity"]=="ISLAND"]

In [32]:
island_data[["housing_median_age","total_rooms","total_bedrooms"]]

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [34]:
# Getting array values
X = island_data[["housing_median_age","total_rooms","total_bedrooms"]].values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [36]:
X_transpose = X.T

In [38]:
X_transpose

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [40]:
XTX = X.dot(X_transpose)
XTX

array([[3077795., 4260640., 3830881., 1807248., 1311577.],
       [4260640., 5916866., 5322889., 2508292., 1817026.],
       [3830881., 5322889., 4788977., 2256364., 1634008.],
       [1807248., 2508292., 2256364., 1064416.,  771140.],
       [1311577., 1817026., 1634008.,  771140.,  559293.]])

In [42]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 4.50889141e+08, -2.65092831e+09,  2.66146909e+09,
        -5.26157398e+08,  5.04760603e+08],
       [ 2.60444475e+11, -8.57212683e+10, -2.18771394e+10,
         5.28097320e+11, -9.96480838e+11],
       [-2.81125831e+11,  9.36268739e+10,  2.24292933e+10,
        -5.69400064e+11,  1.07463035e+12],
       [ 1.50907516e+11, -5.52172767e+10, -6.69134384e+09,
         3.02798151e+11, -5.72439948e+11],
       [-2.33928769e+11,  8.73028262e+10,  8.53028316e+09,
        -4.68398445e+11,  8.85843939e+11]])

In [44]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [46]:
Xti= X_transpose.dot(XTX_inv)
Xti

array([[-0.00292969, -0.01469421,  0.00446415,  0.0267334 ,  0.0057373 ],
       [ 0.08203125, -0.03399658,  0.00515366, -0.09912109, -0.06201172],
       [ 0.02539062, -0.00357056, -0.00726509,  0.04614258, -0.06811523]])

In [48]:
w = Xti.dot(y)
w

array([  15.87753296, -141.87927246,  -28.7399292 ])