 ## ML Zoomcamp

 ### Linear Algebra refresher

 Plan:

 * Vector Operations
 * Multiplication
      * Vector-vector multiplication
      * Matrix-vector multiplication
      * Matrix-matrix multiplication
 * Identity Matrix
 * Inverse

In [2]:
import numpy as np

### Vector Operations

In [4]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [5]:
v = np.array([1,0,0,2])

In [6]:
u + v

array([3, 4, 5, 8])

### Multiplication

In [8]:
u * v

array([ 2,  0,  0, 12])

#### Vector-vector multiplication (Row * Column vector)

In [10]:
v.shape[0]

4

In [11]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0] # ensure the vectors have the same size

    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [12]:
vector_vector_multiplication(u,v)

14.0

In [13]:
u.dot(v)

14

#### MATRIX-VECTOR MULTIPLICATION

In [19]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]    
])

U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [21]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
        
    return result
    

In [23]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [25]:
U.dot(v)

array([14,  5,  5])

#### Matrix-matrix Multiplication

In [30]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [34]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    return result
    

In [36]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [38]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

#### Identity Matrix

In [45]:
I = np.eye(3)

In [47]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [49]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

#### Inverse

In [52]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [56]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [58]:
Vs_inv.dot(Vs) #Multiply a matix with the inverse of that matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])