## ML Zoomcamp

### Introduction to Numpy

Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
  * Comparision
  * Logical operations
* Summarizing operations


In [5]:
import numpy as np
np

<module 'numpy' from 'C:\\Users\\STUDENT\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

### Creating arrays

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [16]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [18]:
a[2]

3

In [23]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi-dimensional arrays

In [35]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
n = np.array([
         [1,20,3],
         [4,5,6],
         [7,8,9]])

In [55]:
n[2] = [1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [59]:
n[:,2] = [0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

### Randomly generated arrays

In [73]:
np.random.seed(2) # FIXING THE RANDOM SEED TO AVOID IT CHANGING
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [75]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [79]:
np.random.seed(2) # FIXING THE RANDOM SEED TO AVOID IT CHANGING
np.random.randint(low = 0, high = 100, size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Elementwise operations

In [81]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [83]:
a + 1

array([1, 2, 3, 4, 5])

In [85]:
a * 3

array([ 0,  3,  6,  9, 12])

In [87]:
a / 3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [95]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [97]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [99]:
a/b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

### Comparison operations

In [106]:
a

array([0, 1, 2, 3, 4])

In [108]:
a >= 2

array([False, False,  True,  True,  True])

In [110]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [112]:
 a > b

array([False, False,  True,  True,  True])

In [114]:
a[a>b]

array([2, 3, 4])

### Summarizing operations

In [116]:
a.min()

0

In [118]:
a.max()

4

In [120]:
a.sum()

10

In [122]:
a.mean()

2.0

In [124]:
a.std()

1.4142135623730951

In [126]:
n.sum() #works for 2d arrays too

35

In [128]:
n.min()

0